name: SoftServe Home Work
on:
  push:
  workflow_dispatch:
jobs:
  First-Test:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'
          
      - name: Show Java version
        run: java -version
        
      - name: Get files from GitHub repositories
        uses: actions/checkout@v4
        
      - name: Show directory
        run: pwd

      - name: List files
        run: ls -la

      - name: Install Dependisies
        run: mvn compile

      - name: Build Application
        run: mvn package -DskipTests

      - name: Test Application
        run: mvn test
